# Building phase
FROM maven:latest AS builder
WORKDIR /app
COPY . .
RUN mvn test
RUN mvn clean package

# Execution phase
FROM openjdk:8-jre

WORKDIR /app
COPY --from=builder /app/target/accenture-techhub-0.0.1-SNAPSHOT.war api-accenture.war

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "api-accenture.war"]